#!/bin/sh
set -e

if ! git diff-index --quiet HEAD; then
  echo "Working tree is dirty."
  exit 1
fi

version="$(git describe --exact-match --tags 2>/dev/null | sed 's/v//')"
if [ -z "$version" ]; then
  echo "No version tag."
  exit 1
fi

echo "Version $version"

date=$(git show -s --format=%cI HEAD)

mkdir -p build
cat >"build/$version.md" <<EOS
---
title: Free License
version: $version
date: $date
summary: terms for free use of projects
---

EOS

sed '/<!--/d' terms.md | # Remove HTML comments.
  sed "s/VERSION/$version/" | # Replace version in URL.
  sed '/^\s*$/d' | # Collapse blank lines.
  awk 'ORS="\n\n"' | # Add single blank lines.
  head -n -1 >> "build/$version.md"

new_version="$(pwd)/build/$version.md"

tmp=$(mktemp -d)
cleanup () {
  rm -rf "$tmp"
}
trap cleanup EXIT

git clone git@github.com:indiecc/indiecc.com "$tmp"
cd "$tmp"
cp "$new_version" "terms/free/$version.md"
git add "terms/free/$version.md"
git commit -m "Free License $version"
git push origin

echo "TODO: Release a new version of the standard deal."
